
        const tryRequire = (path) => {
        	try {
        	const image = require(`${path}`);
        	return image
        	} catch (err) {
        	return false
        	}
        };

        export default {
        
	questionMark: require('./questionMark.png'),
	Feedback_Rectangle33: tryRequire('./Feedback_Rectangle33.png') || require('./questionMark.png'),
	_404notfound_background: tryRequire('./_404notfound_background.png') || require('./questionMark.png'),
	login_background: tryRequire('./login_background.png') || require('./questionMark.png'),
	assets_Ativo11: tryRequire('./assets_Ativo11.png') || require('./questionMark.png'),
	Desktop_Rectangle20: tryRequire('./Desktop_Rectangle20.png') || require('./questionMark.png'),
	mockupapp1_MapMakerItapoSantaCatarinaBrazilStandard: tryRequire('./mockupapp1_MapMakerItapoSantaCatarinaBrazilStandard.png') || require('./questionMark.png'),
	Cadastro__60850611: tryRequire('./Cadastro__60850611.png') || require('./questionMark.png'),
	assets_Vector: tryRequire('./assets_Vector.png') || require('./questionMark.png'),
	mockupapp2_image2: tryRequire('./mockupapp2_image2.png') || require('./questionMark.png'),
	assets_logovetorizado021: tryRequire('./assets_logovetorizado021.png') || require('./questionMark.png'),
	mockupapp1_Line7: tryRequire('./mockupapp1_Line7.png') || require('./questionMark.png'),
	mockupapp1_image1: tryRequire('./mockupapp1_image1.png') || require('./questionMark.png'),
	Header_Line1: tryRequire('./Header_Line1.png') || require('./questionMark.png'),
	mockupapp1_More: tryRequire('./mockupapp1_More.png') || require('./questionMark.png'),
	Desktop_Vector: tryRequire('./Desktop_Vector.png') || require('./questionMark.png'),
	mockupapp1_Location: tryRequire('./mockupapp1_Location.png') || require('./questionMark.png'),
	mockupapp2_Bookmark: tryRequire('./mockupapp2_Bookmark.png') || require('./questionMark.png'),
	Desktop_SlideUp: tryRequire('./Desktop_SlideUp.png') || require('./questionMark.png'),
	mockupapp1_Rectangle55: tryRequire('./mockupapp1_Rectangle55.png') || require('./questionMark.png'),
	mockupapp2_Back: tryRequire('./mockupapp2_Back.png') || require('./questionMark.png'),
	mockupapp2_Calendar: tryRequire('./mockupapp2_Calendar.png') || require('./questionMark.png'),
	Feedback_Star: tryRequire('./Feedback_Star.png') || require('./questionMark.png'),
	mockupapp1_Rectangle56: tryRequire('./mockupapp1_Rectangle56.png') || require('./questionMark.png'),
	mockupapp2_Address: tryRequire('./mockupapp2_Address.png') || require('./questionMark.png'),
	Feedback_Star_1: tryRequire('./Feedback_Star_1.png') || require('./questionMark.png'),
	mockupapp2_Numbers: tryRequire('./mockupapp2_Numbers.png') || require('./questionMark.png'),
	Feedback_Star_2: tryRequire('./Feedback_Star_2.png') || require('./questionMark.png'),
	mockupapp1_Search: tryRequire('./mockupapp1_Search.png') || require('./questionMark.png'),
	mockupapp2_HeartwithPulse: tryRequire('./mockupapp2_HeartwithPulse.png') || require('./questionMark.png'),
	Feedback_Star_3: tryRequire('./Feedback_Star_3.png') || require('./questionMark.png'),
	mockupapp1_Multiply: tryRequire('./mockupapp1_Multiply.png') || require('./questionMark.png'),
	Feedback_Star_4: tryRequire('./Feedback_Star_4.png') || require('./questionMark.png'),
	login_Vector: tryRequire('./login_Vector.png') || require('./questionMark.png'),
	login_1_Vector: tryRequire('./login_1_Vector.png') || require('./questionMark.png'),
	login_Vector_1: tryRequire('./login_Vector_1.png') || require('./questionMark.png'),
	login_1_Vector_1: tryRequire('./login_1_Vector_1.png') || require('./questionMark.png'),
	login_Vector_2: tryRequire('./login_Vector_2.png') || require('./questionMark.png'),
	login_1_Vector_2: tryRequire('./login_1_Vector_2.png') || require('./questionMark.png'),
	login_Vector_3: tryRequire('./login_Vector_3.png') || require('./questionMark.png'),
	login_1_Vector_3: tryRequire('./login_1_Vector_3.png') || require('./questionMark.png'),
	Desktop_Rectangle46: tryRequire('./Desktop_Rectangle46.png') || require('./questionMark.png'),
	Desktop_Start: tryRequire('./Desktop_Start.png') || require('./questionMark.png'),
	Feedback_Rectangle32: tryRequire('./Feedback_Rectangle32.png') || require('./questionMark.png'),
	Feedback_Vector: tryRequire('./Feedback_Vector.png') || require('./questionMark.png'),
	Feedback_Vector_1: tryRequire('./Feedback_Vector_1.png') || require('./questionMark.png'),
	Desktop_Address: tryRequire('./Desktop_Address.png') || require('./questionMark.png'),
	login_Letter: tryRequire('./login_Letter.png') || require('./questionMark.png'),
	Investidores_ExpandArrow: tryRequire('./Investidores_ExpandArrow.png') || require('./questionMark.png'),
	Desktop_Storytelling: tryRequire('./Desktop_Storytelling.png') || require('./questionMark.png'),
	Desktop_Alarm: tryRequire('./Desktop_Alarm.png') || require('./questionMark.png'),
	Investidores_Vector: tryRequire('./Investidores_Vector.png') || require('./questionMark.png'),
	Desktop_Rectangle42: tryRequire('./Desktop_Rectangle42.png') || require('./questionMark.png'),
	Desktop_Line2: tryRequire('./Desktop_Line2.png') || require('./questionMark.png'),
	Desktop_Line3: tryRequire('./Desktop_Line3.png') || require('./questionMark.png'),
	Desktop_Line4: tryRequire('./Desktop_Line4.png') || require('./questionMark.png'),
	Desktop_Forward: tryRequire('./Desktop_Forward.png') || require('./questionMark.png'),
	Desktop_Vector_1: tryRequire('./Desktop_Vector_1.png') || require('./questionMark.png'),
	Desktop_mockupcel12: tryRequire('./Desktop_mockupcel12.png') || require('./questionMark.png'),
	Desktop_Country: tryRequire('./Desktop_Country.png') || require('./questionMark.png'),
	Desktop_SearchProperty: tryRequire('./Desktop_SearchProperty.png') || require('./questionMark.png'),
	Desktop_NotificationCenter: tryRequire('./Desktop_NotificationCenter.png') || require('./questionMark.png'),
	Desktop_Vector_2: tryRequire('./Desktop_Vector_2.png') || require('./questionMark.png'),
	Desktop_mockupcel22: tryRequire('./Desktop_mockupcel22.png') || require('./questionMark.png'),
	Desktop_Line5: tryRequire('./Desktop_Line5.png') || require('./questionMark.png'),
	Desktop_Line6: tryRequire('./Desktop_Line6.png') || require('./questionMark.png'),
	Desktop_Rectangle51: tryRequire('./Desktop_Rectangle51.png') || require('./questionMark.png'),
	Desktop_Rectangle52: tryRequire('./Desktop_Rectangle52.png') || require('./questionMark.png'),
	Desktop_Rectangle59: tryRequire('./Desktop_Rectangle59.png') || require('./questionMark.png'),
	Desktop_Rectangle60: tryRequire('./Desktop_Rectangle60.png') || require('./questionMark.png'),
	Desktop_Rectangle61: tryRequire('./Desktop_Rectangle61.png') || require('./questionMark.png'),
	Desktop_BackArrow: tryRequire('./Desktop_BackArrow.png') || require('./questionMark.png'),
	Desktop_Instagram: tryRequire('./Desktop_Instagram.png') || require('./questionMark.png'),
	Desktop_Facebook: tryRequire('./Desktop_Facebook.png') || require('./questionMark.png'),
	Desktop_TwitterX: tryRequire('./Desktop_TwitterX.png') || require('./questionMark.png'),
	Desktop_marvetor1: tryRequire('./Desktop_marvetor1.png') || require('./questionMark.png'),
}