-- Drop das Tabelas
DROP TABLE Form_Feedback CASCADE CONSTRAINTS;
DROP TABLE Investidor CASCADE CONSTRAINTS;
DROP TABLE Login CASCADE CONSTRAINTS;
DROP TABLE Ocorrencia_Animal CASCADE CONSTRAINTS;
DROP TABLE Ocorrencia_Poluente CASCADE CONSTRAINTS;
DROP TABLE Animal CASCADE CONSTRAINTS;
DROP TABLE Condicao_Animal CASCADE CONSTRAINTS;
DROP TABLE Newsletter CASCADE CONSTRAINTS;
DROP TABLE Usuario CASCADE CONSTRAINTS;
DROP TABLE Tipo_Residuo CASCADE CONSTRAINTS;
DROP TABLE Visitante CASCADE CONSTRAINTS;

-- DDL - Criação das tabelas
-- Visitante
CREATE TABLE Visitante (
  id_visitante INTEGER GENERATED BY DEFAULT AS IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY,
  hora_entrada_vis TIMESTAMP,
  hora_saida_vis TIMESTAMP
);

-- Usuario
CREATE TABLE Usuario (
  id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY,
  nome_usuario VARCHAR2(80) NOT NULL,
  sobrenome_usuario VARCHAR2(80) NOT NULL,
  email_usuario VARCHAR2(80) UNIQUE NOT NULL,
  senha_usuario VARCHAR2(80) NOT NULL,
  tel_usuario VARCHAR2(30) NOT NULL,
  id_visitante INTEGER REFERENCES Visitante(id_visitante)
);

-- Login
CREATE TABLE Login (
  id_login INTEGER GENERATED BY DEFAULT AS IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY,
  email_login VARCHAR2(80) NOT NULL,
  senha_login VARCHAR2(80) NOT NULL,
  data_login TIMESTAMP,
  sucesso_login CHAR(1) DEFAULT 'N' NOT NULL,
  id_visitante INTEGER REFERENCES Visitante(id_visitante)
);

-- Condicao_Animal
CREATE TABLE Condicao_Animal (
  id_condicao INTEGER GENERATED BY DEFAULT AS IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY,
  desc_condicao VARCHAR2(80) NOT NULL
);

-- Animal
CREATE TABLE Animal (
  id_animal INTEGER GENERATED BY DEFAULT AS IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY,
  nome_animal VARCHAR2(90),
  especie_animal VARCHAR2(120),
  desc_animal VARCHAR2(255)
);

-- Tipo_Residuo
CREATE TABLE Tipo_Residuo (
  id_tipo_residuo INTEGER GENERATED BY DEFAULT AS IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY,
  nome_tipo_residuo VARCHAR2(90) NOT NULL,
  desc_tipo_residuo VARCHAR2(120) NOT NULL
);


-- Ocorrencia
CREATE TABLE Ocorrencia_Animal (
  id_ocorr INTEGER GENERATED BY DEFAULT AS IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY,
  nome_ocorr VARCHAR2(255),
  email_ocorr VARCHAR2(80),
  tel_ocorr VARCHAR2(30),
  id_animal INTEGER REFERENCES Animal(id_animal),
  id_condicao_animal INTEGER REFERENCES Condicao_Animal(id_condicao),
  first_aid_ocorr VARCHAR2(10), -- Sim ou Não
  cep_ocorr VARCHAR2(20),
  estado_ocorr VARCHAR2(40),
  cidade_ocorr VARCHAR2(80),
  rua_ocorr VARCHAR2(255),
  complemento_ocorr VARCHAR2(255), -- complemento do endereço
  msg_ocorr VARCHAR2(255),
  foto_ocorr VARCHAR2(255), 
  lat_ocorr VARCHAR2(50),
  long_ocorr VARCHAR2(50),
  data_solicitacao TIMESTAMP,
  status_ocorr CHAR(1) CHECK (status_ocorr IN ('0', '1')),
  id_visitante INTEGER REFERENCES Visitante(id_visitante)
);


CREATE TABLE Ocorrencia_Poluente (
  id_ocorr INTEGER GENERATED BY DEFAULT AS IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY,
  nome_ocorr VARCHAR2(255),
  email_ocorr VARCHAR2(80),
  tel_ocorr VARCHAR2(30),
  id_tipo_residuo INTEGER REFERENCES Tipo_Residuo(id_tipo_residuo),
  qtd_residuo_ocorr NUMBER,
  area_perigo_ocorr VARCHAR2(20), -- Sim ou Não
  cep_ocorr VARCHAR2(20),
  estado_ocorr VARCHAR2(40),
  cidade_ocorr VARCHAR2(80),
  rua_ocorr VARCHAR2(255),
  complemento_ocorr VARCHAR2(255),
  msg_ocorr VARCHAR2(255),
  foto_ocorr VARCHAR2(255),
  lat_ocorr VARCHAR2(50),
  long_ocorr VARCHAR2(50),
  data_solicitacao TIMESTAMP,
  status_ocorr CHAR(1) CHECK (status_ocorr IN ('0', '1')),
  id_visitante INTEGER REFERENCES Visitante(id_visitante)
);

-- Investidor
CREATE TABLE Investidor (
  id_investidor INTEGER GENERATED BY DEFAULT AS IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY,
  nome_inv VARCHAR2(80) NOT NULL,
  email_inv VARCHAR2(80) NOT NULL,
  telefone_inv VARCHAR2(30) NOT NULL,
  nome_empresa_inv VARCHAR2(80) NOT NULL,
  quantia_contribuida_inv DECIMAL(10, 2) NOT NULL,
  data_investimento_inv TIMESTAMP NOT NULL,
  msg_inv VARCHAR2(80) NOT NULL,
  id_visitante INTEGER REFERENCES Visitante(id_visitante)
);

-- Form_Feedback
CREATE TABLE Form_Feedback (
  id_feedback INTEGER GENERATED BY DEFAULT AS IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY,
  nome_feedback VARCHAR2(80) NOT NULL,
  email_feedback VARCHAR2(80) NOT NULL,
  tel_feedback VARCHAR2(30) NOT NULL,
  msg_feedback VARCHAR2(255) NOT NULL,
  nota_feedback NUMBER(1) CHECK (nota_feedback BETWEEN 1 AND 5),
  data_feedback TIMESTAMP NOT NULL,
  id_visitante INTEGER REFERENCES Visitante(id_visitante)
);



-- Newsletter
CREATE TABLE Newsletter (
  id_news INTEGER GENERATED BY DEFAULT AS IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY,
  email_news VARCHAR2(80),
  data_envio_news TIMESTAMP,
  status_news CHAR(1) CHECK (status_news IN ('0', '1')),
  id_visitante INTEGER REFERENCES Visitante(id_visitante)
);

-- Inserts para a GLOBAL
-- Inserção de dados na tabela Animal
INSERT INTO Animal (nome_animal, especie_animal, desc_animal) 
VALUES ('Golfinho', 'Delphinus delphis', 'Golfinho comum encontrado nos oceanos tropicais e temperados.');

INSERT INTO Animal (nome_animal, especie_animal, desc_animal) 
VALUES ('Baleia', 'Balaenoptera musculus', 'Baleia azul, o maior animal existente, encontrado em todos os oceanos.');

INSERT INTO Animal (nome_animal, especie_animal, desc_animal) 
VALUES ('Tartaruga', 'Chelonia mydas', 'Tartaruga marinha verde, encontrada em mares tropicais e subtropicais.');

INSERT INTO Animal (nome_animal, especie_animal, desc_animal) 
VALUES ('Foca', 'Phoca vitulina', 'Foca comum encontrada nas regiões costeiras do Atlântico Norte e do Pacífico Norte.');


-- Inserção de dados na tabela Condicao_Animal
INSERT INTO Condicao_Animal (desc_condicao) 
VALUES ('Vivo');

INSERT INTO Condicao_Animal (desc_condicao) 
VALUES ('Morto');

INSERT INTO Condicao_Animal (desc_condicao) 
VALUES ('Ferido');

INSERT INTO Condicao_Animal (desc_condicao) 
VALUES ('Doente');

-- Inserção de dados na tabela Tipo_Residuo
INSERT INTO Tipo_Residuo (nome_tipo_residuo, desc_tipo_residuo) 
VALUES ('Plástico', 'Resíduo de material plástico, como garrafas PET e sacolas.');

INSERT INTO Tipo_Residuo (nome_tipo_residuo, desc_tipo_residuo) 
VALUES ('Metal', 'Resíduo de material metálico, como latas de alumínio e aço.');

INSERT INTO Tipo_Residuo (nome_tipo_residuo, desc_tipo_residuo) 
VALUES ('Vidro', 'Resíduo de material de vidro, como garrafas e frascos.');

INSERT INTO Tipo_Residuo (nome_tipo_residuo, desc_tipo_residuo) 
VALUES ('Papel', 'Resíduo de material de papel, como jornais, revistas e caixas de papelão.');

INSERT INTO Tipo_Residuo (nome_tipo_residuo, desc_tipo_residuo) 
VALUES ('Orgânico', 'Resíduo orgânico, como restos de comida e cascas de frutas.');

-- Insert de Usuários
INSERT INTO Usuario (nome_usuario, sobrenome_usuario, email_usuario, senha_usuario, tel_usuario)
VALUES ('Patricia', 'Naomi', 'pati.fofinha@oie.com', '!Fofinha123', '11961393029');

COMMIT;
